### ISSUE TITLE
React Native "Requiring unknown module "Crypto"

### ISSUE THREAD

**Issue by mjniuz** [joaquimserafim/json-web-token#10]
Hello

I use this library on my react native but i got the error message

Requiring unknown module "crypto". If you are sure the module is there, try restarting the packager or running "npm install"

I already install crypto 
https://www.npmjs.com/package/react-native-crypto

Can you help me for this?

thanks

**Comment by joaquimserafim** [comment]
Hi,

I'll take a look

Take care
Joaquim

**Comment by joaquimserafim** [comment]
hey @mjniuz which version of NodeJS you're using?

**Comment by mjniuz** [comment]
Node v6.3.1

**Comment by joaquimserafim** [comment]
sorry mate but this sounds definitely a react-native issue and I am not a react expert I'll try to get some react guys on this but I don't promise anything 


Take care

**Comment by anonrig** [comment]
Crypto is a native nodejs library. On the other hand, you're using a native nodejs library on a interface that runs on WKWebView. That's why you shouldn't use this library on a React-Native app.

**Comment by joaquimserafim** [comment]
thanks a lot @anonrig 👍  I am closing this issue based on your explanation
