### ISSUE TITLE
Extend support for additional JWT headers

### ISSUE THREAD

**Issue by callmepjs** [joaquimserafim/json-web-token#11]
I've been using this library for my JWT tokens and have found it really useful. Recently came across a requirement to include a key id (kid) of the key used to sign the JWT token in the header section (Ref: Section 5.1 @ http://self-issued.info/docs/draft-jones-json-web-token-01.html) 

For example:
```
	{
	  "alg": "RS256",
	  "typ": "JWT",
	  "kid": "DZjSgUGcezHMQ1rZAtyLhg=="  // Key ID used to sign the token
	}
```
It would be awesome to extend the library to add additional headers to the JWT header section. I already have a patch ready for review if you think this is a useful addition to your library.

**Comment by joaquimserafim** [comment]
Hi there,
thanks for using this lib 👍 and yes please send a PR 

take care

**Comment by callmepjs** [comment]
Thanks for the quick response. I've submitted a pull request. Would
appreciate if you can take a look and release a new version of the library.

Cheers,
Prabjeet

**Comment by joaquimserafim** [comment]
sorry for the lateness, version `2.1.3` is published see the README for further understanding how to set the headers, thanks mate
