### ISSUE TITLE
Unable to resolve module crypto with React-Native

### ISSUE THREAD

**Issue by RyanMitchellWilson** [joaquimserafim/json-web-token#14]
Getting `Unable to resolve module crypto from /<PathToApp>/node_modules/json-web-token/index.js: Module does not exist in the module map`

Using:
json-web-token - 2.1.3
React-Native - 0.41.0

**Comment by joaquimserafim** [comment]
Hi mate thank you for using `json-web-token` and you can check @anonrig answer in the issue [10](https://github.com/joaquimserafim/json-web-token/issues/10)
