### ISSUE TITLE
The algorithm is not supported!

### ISSUE THREAD

**Issue by Progyan1997** [joaquimserafim/json-web-token#15]
Getting this error while decoding the web-token

**Using RSA512**
**.pem public key**

**Comment by joaquimserafim** [comment]
Hi thanks for using this module, now about the issue RSA512 is not part of the available algorithms (and is neither required on the IETF proposal for [JWA](https://tools.ietf.org/html/rfc7518#section-3)) for this module but a PR is very welcome 👍

thanks
