### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by shiva-p17** [joaquimserafim/json-web-token#16]
Hi,

Whenever I'm checking the token on https://jwt.io/, the site is throwing the error that invalid signature.
And am generating the token as follows,
`jwToken.issue({email: mymail})` 
Do I miss anything?

Thanks in advance.
Shiva.P

**Comment by joaquimserafim** [comment]
Hi mate,
this module don't exposes the method `issue` only the methods `encode` and `decode`

thanks
