### ISSUE TITLE
Security Issue with dependency

### ISSUE THREAD

**Issue by faonbr** [joaquimserafim/json-web-token#18]
This package uses 
  "base64-url": "^1.2.2".

Running npm audit command shows:
                       === npm audit security report ===
                                 Manual Review
             Some vulnerabilities require your attention to resolve
          Visit https://go.npm.me/audit-guide for additional guidance

  High            Out-of-bounds Read
  Package         base64-url
  Patched in      >=2.0.0
  Dependency of   json-web-token
  Path            json-web-token > base64-url
  More info       https://nodesecurity.io/advisories/660

Please, would you mind to update it to the latest version?

**Comment by joaquimserafim** [comment]
Hi mate, thanks for the heads up, this issue is due some dev modules in that module, I will get a fix
