### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by vixson** [joaquimserafim/json-web-token#22]
### Missing Module

ERROR in ./node_modules/json-web-token/index.js
Module not found: Error: Can't resolve 'crypto' in 'C:\folder\project\node_modules\json-web-token'

But the [_crypto_ ](https://www.npmjs.com/package/crypto)is installed.

**Comment by joaquimserafim** [comment]
Hi mate can you provide the output of `nom ls` plz, thanks
