### ISSUE TITLE
Security Issue - Request For Contact Details

### ISSUE THREAD

**Issue by PinkDraconian** [joaquimserafim/json-web-token#32]
Hi there,

I'd like to report a security issue in this library. How can I contact you privately?

Kind regards
PinkDraconian

**Comment by joaquimserafim** [comment]
on X pls, I am following u now

**Comment by PinkDraconian** [comment]
Thank you for the quick response. I've sent you all the required details on X.

**Comment by PinkDraconian** [comment]
Thank you, I've now reported it there. I'll close this issue.
