### ISSUE TITLE
Handle Token error

### ISSUE THREAD

**Issue by sudhirbitsgoa** [joaquimserafim/json-web-token#9]
If client sends wrong token this error should be caught instead of sending 

```
500  Internal server error
SyntaxError: Unexpected token 
```
Any way to handle ?

**Comment by sudhirbitsgoa** [comment]
should embed in try catch block.

```
try {
         jwt.decode(secret, wrongToken, function () {....
     } catch (err) {
        res.status(401).send('Invalid token');
    }
```

**Comment by joaquimserafim** [comment]
hi @sudhirbitsgoa this module should not throw an exception like that one I've changed the behavior when call `decode` and is a bad token or header (i.e., is not a json) then will return a generic error on the callback

take care
